# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
#tap "homebrew/cask-eid"
tap 'homebrew/bundle'

# Binaries
brew "ack"
brew "awscli"
brew "bash"
brew "bat"
brew 'coreutils' # Those that come with macOS are outdated
brew 'git'
brew 'pkg-config'
brew 'grep'
brew 'htop'
brew 'mackup'
brew 'mas'
brew 'trash'
brew 'tree'
brew 'tmux'
brew 'zsh'
brew 'zsh-completions'
#brew 'openldap'
#brew 'libiconv'

# Development
brew 'php'
brew 'php@8.0'
brew 'php@7.4'
brew 'composer'
brew 'node'
brew 'nvm'
brew "docker"
brew "docker-compose", link: false
brew "docker-machine"
brew "terraform"

# Apps
cask 'brave'
cask 'firefox'
cask 'google-chrome'
cask 'alfred'
cask 'aws-vpn-client'
cask 'docker'
cask 'phpstorm'
cask '1password'
#cask 'dropbox'
cask 'sequel-ace'
cask 'iterm2'
cask 'spotify'
cask 'vlc'
cask 'whatsapp'
cask 'teamviewer'
#cask 'eid-be'
#cask 'eid-be-viewer'
cask 'tableplus'
cask 'visual-studio-code'
